" Install packages and configuration
call plug#begin()
Plug 'tpope/vim-surround' " The Pope's gift to man
Plug 'morhetz/gruvbox'
"Plug 'joshdick/onedark.vim'
"Plug 'arcticicestudio/nord-vim'
"Plug 'lifepillar/vim-solarized8'
Plug 'preservim/nerdtree' " We want that tree action
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tpope/vim-fugitive', { 'on': 'Gstatus' } " Git badassery
"Plug 'pangloss/vim-javascript', { 'for': 'javascript' } " Javascript support
"Plug 'leafgarland/typescript-vim' " Typescript lang
Plug 'ianks/vim-tsx'
Plug 'maxmellon/vim-jsx-pretty'
"Plug 'vim-ruby/vim-ruby' " Ruby support
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'scrooloose/nerdcommenter' " Comment lines
Plug '/usr/local/opt/fzf' " Searching, need to install fzf first
Plug 'junegunn/fzf.vim' " Fzf plugin to interact with cmd tool
"Plug 'aklt/plantuml-syntax'
Plug 'aquach/vim-http-client'
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }
Plug 'junegunn/vim-easy-align'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'sheerun/vim-polyglot'
" Need to look at why this is not working correctly
" Plug 'dart-lang/dart-vim-plugin'

" COC Plugins
Plug 'neoclide/coc-tsserver', {'do': 'yarn install --frozen-lockfile'}
Plug 'neoclide/coc-yaml', {'do': 'yarn install --frozen-lockfile'}
Plug 'iamcco/coc-flutter', {'do': 'yarn install --frozen-lockfile'}

let g:coc_global_extensions=[ 'coc-omnisharp' ]
" Need to look at why this is not working correctly
" Plug 'iamcco/coc-flutter', {'do': 'yarn install --frozen-lockfile'}

call plug#end()

" Settings
let mapleader = " "
if has('mac')
  let g:clipboard = {'copy': {'+': 'pbcopy', '*': 'pbcopy'}, 'paste': {'+': 'pbpaste', '*': 'pbpaste'}, 'name': 'pbcopy', 'cache_enabled': 0}
endif
set clipboard+=unnamedplus
set completeopt=menu,preview,longest,noinsert
set modelines=0
set history=500
set autoread
set showmatch
set splitbelow splitright
set mouse=a

if !has('nvim')
	set ttymouse=xterm2
endif

" User Interface
set colorcolumn=120
set cursorline
set title
set number
set lazyredraw
set signcolumn=yes
set showcmd
set hidden
set showmode
set updatetime=300
set nobackup
set writebackup
set shortmess+=c
set relativenumber

if has("gui_running")
  set guifont=Source\ Code\ Pro:h12
  set guioptions-=m " no menu
  set guioptions-=T " no toolbar
  set guioptions-=r " no scrollbar on the right
  set guioptions-=L " no scrollbar on the right
  set guioptions-=b " no scrollbar on the bottom
endif

if (has("termguicolors"))
  set termguicolors
endif

syntax on
set bg=dark
colorscheme gruvbox
set termguicolors
let g:airline_powerline_fonts = 1

" air-line
let g:airline_powerline_fonts = 1

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

" airline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''

"General UI

" Files and Backups
set noswapfile
set backupdir=.,/tmp
set undodir=~/.vim/.tmp,~/tmp,~/.tmp,/tmp
set wildignore=.svn,CVS,.git,*.swp,*.jpg,*.png,*.gif,*.pdf,*.bak
set suffixes+=.bak
set undofile

" Text Formatting
set smartcase
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set ignorecase
set hlsearch
set nowrap

" Keybindings

" General Keybindings
map <leader><leader> :
imap jk <ESC>
nnoremap <backspace> <C-^>
nnoremap ` '
nnoremap ' `
imap <C-s> <C-o>:w!<CR>
imap <C-v> <ESC>"+gP
vmap <C-c> "+y
inoremap <expr> <TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr> <S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

" Project management
nmap <leader>pf :Files<CR>
nmap <leader>pp :source ~/.vim/sessions/
nmap <leader>ps :mksession! ~/.vim/sessions/
nmap <leader>pt :NERDTreeToggle<CR>

map \ :NERDTreeToggle<CR>

" Git/Fugitive keybindings
nnoremap <leader>gc :Gcommit<CR>
nnoremap <leader>gC :Git checkout
nnoremap <leader>gf :Gfetch<CR>
nnoremap <leader>gF :!git pull --rebase<CR>
nnoremap <leader>gP :Gpush
nnoremap <leader>gs :Gstatus<CR>

" Window bindings
nnoremap <leader>wh <C-w>h
nnoremap <leader>wj <C-w>j
nnoremap <leader>wk <C-w>k
nnoremap <leader>wl <C-w>l
nnoremap <leader>wo <C-w>o
nnoremap <leader>wc <C-w>c
nnoremap <leader>ws <C-w>s
nnoremap <leader>wv <C-w>v

" Buffer bindings
nmap <leader>d :bp<bar>sp<bar>bn<bar>bd<CR>
nmap <leader>bd :bd!<CR>
nmap <leader>bb :Buffers<CR>
nmap <leader>bn :bn!<CR>
nmap <leader>bp :bp!<CR>
nmap <leader>bs :call Scratch()<CR>

" To avoid generating too much entropy
nmap <leader>qq :wqa!<CR>
"nmap <leader><Esc> :q!<CR>
nmap <leader>/ :noh<CR>

" File based
nmap <leader>ff :edit
nmap <leader>fs :w!<CR>
nmap <leader>ft :NERDTreeFind<CR>
nmap <leader>feR :source ~/.vimrc<CR>
nmap <leader>fed :edit ~/.vimrc<CR>

" Searching
nnoremap <Leader>sw :Rg <C-r><C-w>
nnoremap <Leader>sg :Rg<CR>
nnoremap <Leader>sb :BLines<CR>
tnoremap <Esc> <C-\><C-n>

" Nice scratch buffer on read command
:command! -nargs=* -complete=shellcmd R new | setlocal buftype=nofile bufhidden=hide noswapfile | r !<args>

" FZF configuration
let $FZF_DEFAULT_COMMAND = 'rg --hidden --files'
" Files with preview
command! -bang -nargs=* -complete=dir Files
      \ call fzf#vim#files(<q-args>, fzf#vim#with_preview('right:50%:hidden', '?'), <bang>0)
" Grep with preview
command! -bang -nargs=* Rg
      \ call fzf#vim#grep(
      \ 'rg --column --line-number --no-heading --color=always '.shellescape(<q-args>), 1,
      \ fzf#vim#with_preview({'options': '--delimiter : --nth 4..'},'right:50%:hidden', '?'))

" LSP configuration
let g:coc_force_debug = 1
inoremap <silent><expr> <c-space> coc#refresh()
nmap <silent> [c <Plug>(coc-diagnostic-prev)
nmap <silent> ]c <Plug>(coc-diagnostic-next)
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gh <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
nmap <silent> <F2> <Plug>(coc-rename)
nmap <leader>qf <Plug>(coc-fix-current)
nnoremap <silent> K :call <SID>show_documentation()<CR>
autocmd CursorHold * silent call CocActionAsync('highlight')
command! -nargs=0 JestCurrent :call CocAction('runCommand', 'jest.fileTest', ['%'])

function! s:show_documentation()
  if &filetype == 'vim'
    execute 'h '.expand('<cword>')
  else
    call CocActionAsync('doHover')
  endif
endfunction

" Tab now opens dirs in nerdtree
autocmd FileType nerdtree map <buffer> <tab> <CR>
let NERDTreeShowHidden = 1
let NERDTreeWinSize = 50

" Snippets - Really don't use these enough
let g:UltiSnipsExpandTrigger="<C-j>"
let g:UltiSnipsJumpForwardTrigger="<C-j>"
let g:UltiSnipsJumpBackwardTrigger="<C-k>"

let g:plantuml_executable_script='java -jar ~/plantuml.jar -tsvg'
let g:http_client_verify_ssl=0

" use python to format xml
command! FormatXML :%!python3 -c "import xml.dom.minidom, sys; print(xml.dom.minidom.parse(sys.stdin).toprettyxml())"
command! FormatJSON :%!jq

" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)
" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)

" COC Config stuff
function! SetupCommandAbbrs(from, to)
  exec 'cnoreabbrev <expr> '.a:from
        \ .' ((getcmdtype() ==# ":" && getcmdline() ==# "'.a:from.'")'
        \ .'? ("'.a:to.'") : ("'.a:from.'"))'
endfunction

" Use C to open coc config
call SetupCommandAbbrs('C', 'CocConfig')

" Helper functions

" Helper function to create a new scratch buffer
function! Scratch()
    split
    noswapfile hide enew
    setlocal buftype=nofile
    setlocal bufhidden=hide
    "setlocal nobuflisted
    "lcd ~
    file scratch
endfunction
