export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

case `uname` in
  Darwin)
    # commands for OS X go hereo
  export GOPATH=$HOME/Workspace/Go
  export PATH=$PATH:$GOPATH/bin
  export PATH=$PATH:$GOROOT/bin

	export PATH="$PATH:$HOME/Workspace/github.com/flutter/bin"
  export PATH="$PATH:$HOME/Workspace/flutter/bin"

	export PATH=$PATH:/Users/bharvey/Library/Python/2.7/bin

  export ANDROID_HOME=/usr/local/share/android-sdk
  export PATH="$PATH:/Users/benharvey/.dotnet/tools"

  unset GOROOT
  ;;
  Linux)
    # commands for Linux go here
	#export GOROOT=/usr/local/go/bin
	export PATH=$PATH:/usr/local/go/bin
	export GOPATH=$HOME/Workspace/Go
	export GOBIN=$GOPATH/bin
	export PATH=$PATH:$GOPATH
	export PATH=$PATH:$GOBIN

  unset GOROOT

	export PATH="$PATH:$HOME/Workspace/github.com/flutter/bin"
  export PATH="$PATH:$HOME/Workspace/flutter/bin"

  export ANDROID_HOME=$HOME/Android/Sdk
  export ANDROID_SDK=$HOME/Android/Sdk
  export ANDROID_SDK_ROOT=$HOME/Android/Sdk

  # avdmanager, sdkmanager
  export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin

  # adb, logcat
  export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools

  # emulator
  export PATH=$PATH:$ANDROID_SDK_ROOT/emulator

  export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

  # ensure android is in PAth
  export PATH="$HOME/Android/Sdk:$PATH"

  ;;
  FreeBSD)
    # commands for FreeBSD go here
  ;;
esac

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

GPG_TTY=$(tty)
export GPG_TTY
if [ -e /Users/ben/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/ben/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
