* Inbox
** TODO Setup the yabai window manager

[[file:~/.configuration/nix/darwin-configuration.nix::TODO: Add config for yabai window manager. See todo.org for details]]

Have already found some config that should work for this. At the moment yabai is not compiling correctly. Suspect this might have something to do with being on m1

#+BEGIN_SRC
services.yabai = {
  enable = true;
  package = pkgs.yabai;
  config = {
    mouse_follows_focus = "off";
    focus_follows_mouse = "off";
    window_placement = "second_child";
    window_topmost = "off";
    window_opacity = "off";
    window_opacity_duration = 0.0;
    window_shadow = "on";
    window_border = "off";
    window_border_placement = "inset";
    window_border_width = 4;
    window_border_radius = -1.0;
    active_window_border_topmost = "off";
    active_window_border_color = "0xff775759";
    normal_window_border_color = "0xff505050";
    insert_window_border_color = "0xffd75f5f";
    active_window_opacity = 1.0;
    normal_window_opacity = 0.9;
    split_ratio = 0.5;
    auto_balance = "on";
    mouse_modifier = "fn";
    mouse_action1 = "move";
    mouse_action2 = "resize";
    layout = "bsp";
    top_padding = 5;
    bottom_padding = 5;
    left_padding = 5;
    right_padding = 5;
    window_gap = 5;
  };
  extraConfig = ''
      # rules
      yabai -m rule --add app='System Preferences' manage=off

      # Any other arbitrary config here
    '';
};

services.skhd = {
  enable = true;
  package = pkgs.skhd;
  skhdConfig = builtins.readFile "${config_home}/dotfiles/skhdrc";
};
#+END_SRC
** TODO Kitty doesn't compile with apple m1

[[file:~/.configuration/nix/home.nix::pkgs.kitty # TODO: Does compile with apple m1]]

- Have a look into this and work out why its not compiling or find a work around
** DONE Fix this failing install

[[file:~/.configuration/nix/home.nix::pkgs.ansible TODO: Fix this]]

This fails to install for some reason. Investigate some more and fix what might be going wrong

- Fixed. Installed ansible with a python package
** TODO Get this working

[[file:~/.configuration/nix/home.nix::TODO: Get go packages working here]]

Tried getting this working but it seems that the packages are not getting installed correctly. Currently using pkgs.gopls to get this working
** TODO Create mac and ubuntu specific files

- This setting breaks when trying to run this config file on ubuntu
- Update file so that it has OS specific config or create a seperate file for each OS

[[file:~/.configuration/dotfiles/tmux.conf::set-option -g default-command "reattach-to-user-namespace -l zsh"]]
