* Inbox
** TODO Recreate the secrets dir

Looks like the secrets directory got lost at some point. Find this and recreate so that some of this config works

** TODO Get this working with zsh-vi-mode

There is a plugin for zsh that we are using that enables vi on the shell prompt. This looks like it is not interacting well with fzf. Likely have to find that correct location of the fzf.sh file.

This will likely fix things
https://github.com/jeffreytse/zsh-vi-mode#execute-extra-commands

** TODO Have a look at this for adding node_modules to personal config
https://github.com/nocoolnametom/nixos-configuration/tree/main/myPkgs/development/node-packages

This could be a good way of managing the node_modules that are installed globally

** TODO Setup the yabai window manager

[[file:~/.configuration/nix/darwin-configuration.nix::TODO: Add config for yabai window manager. See todo.org for details]]

Have already found some config that should work for this. At the moment yabai is not compiling correctly. Suspect this might have something to do with being on m1

#+BEGIN_SRC
services.yabai = {
  enable = true;
  package = pkgs.yabai;
  config = {
    mouse_follows_focus = "off";
    focus_follows_mouse = "off";
    window_placement = "second_child";
    window_topmost = "off";
    window_opacity = "off";
    window_opacity_duration = 0.0;
    window_shadow = "on";
    window_border = "off";
    window_border_placement = "inset";
    window_border_width = 4;
    window_border_radius = -1.0;
    active_window_border_topmost = "off";
    active_window_border_color = "0xff775759";
    normal_window_border_color = "0xff505050";
    insert_window_border_color = "0xffd75f5f";
    active_window_opacity = 1.0;
    normal_window_opacity = 0.9;
    split_ratio = 0.5;
    auto_balance = "on";
    mouse_modifier = "fn";
    mouse_action1 = "move";
    mouse_action2 = "resize";
    layout = "bsp";
    top_padding = 5;
    bottom_padding = 5;
    left_padding = 5;
    right_padding = 5;
    window_gap = 5;
  };
  extraConfig = ''
      # rules
      yabai -m rule --add app='System Preferences' manage=off

      # Any other arbitrary config here
    '';
};

services.skhd = {
  enable = true;
  package = pkgs.skhd;
  skhdConfig = builtins.readFile "${config_home}/dotfiles/skhdrc";
};
#+END_SRC
** TODO Kitty doesn't compile with apple m1

[[file:~/.configuration/nix/home.nix::pkgs.kitty # TODO: Does compile with apple m1]]

- Have a look into this and work out why its not compiling or find a work around
