# Include OS specific tasks
- include: macos.yml
  when: ansible_distribution == "MacOSX"
#- include: ubuntu.yml
#  when: ansible_distribution != "MacOSX"

# These are mainly to get the emacs tooling working correctly
- name: Install golang package gocode
  environment:
    GOPATH: "{{ lookup('env','HOME') }}/Workspace/Go"
  shell: >
    go get -u github.com/motemen/gore/cmd/gore

- name: Install golang package godoc
  environment:
    GOPATH: "{{ lookup('env','HOME') }}/Workspace/Go"
  shell: >
    go get -u github.com/stamblerre/gocode

- name: Install golang package goimports
  environment:
    GOPATH: "{{ lookup('env','HOME') }}/Workspace/Go"
  shell: >
    go get -u golang.org/x/tools/cmd/goimports

- name: Install golang package gorename
  environment:
    GOPATH: "{{ lookup('env','HOME') }}/Workspace/Go"
  shell: >
    go get -u golang.org/x/tools/cmd/gorename

- name: Install golang package guru
  environment:
    GOPATH: "{{ lookup('env','HOME') }}/Workspace/Go"
  shell: >
    go get -u golang.org/x/tools/cmd/guru

- name: Install golang package gotests
  environment:
    GOPATH: "{{ lookup('env','HOME') }}/Workspace/Go"
  shell: >
    go get -u github.com/cweill/gotests/...

- name: Install golang package gomodifytags
  environment:
    GOPATH: "{{ lookup('env','HOME') }}/Workspace/Go"
  shell: >
    go get -u github.com/fatih/gomodifytags
