---
- hosts: servers
  become: true
  gather_facts: true
  vars:
    repo_url: git@gitlab.com:benharvey/configuration.git
    branch: master
  roles:
    - authorised_keys
  pre_tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Copy configuration repo to the server
      become: true
      copy:
        src: "{{ lookup('env','HOME') }}/.configuration"
        dest: /home/ben/
        owner: ben
        group: ben
        mode: 0755
