---
- hosts: localhost
  #  gather_facts: true
  vars:
    repo_url: git@gitlab.com:benharvey/configuration.git
    branch: master
  roles:
    - git
    - ssh
    - packages
    - emacs
    - org
    - dirs
    - node
    - fzf
    - zsh
    - golang
    - vim
    - tmux
    - flutter
    - mail
