---
# Include OS specific tasks
- include: mac.yml
  when: ansible_distribution == "MacOSX"
- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Checking out doom emacs
  ansible.builtin.git:
    repo: "https://github.com/hlissner/doom-emacs"
    dest: "{{ lookup('env','HOME') }}/.emacs.d"
    version: develop

- name: Recursively remove directory for .doom.d
  file:
    path: "{{ lookup('env','HOME') }}/.doom.d"
    state: absent

- name: Link .doom.d
  file:
    src: "{{ lookup('env','HOME') }}/.configuration/dotfiles/doom.d"
    dest: "{{ lookup('env','HOME') }}/.doom.d"
    state: link

- name: Install doom emacs
  command: "{{ lookup('env','HOME') }}/.emacs.d/bin/doom sync"
  register: shell_result
  retries: 3
  delay: 5

- debug:
    var: shell_result.stdout_lines

- include: mac-post-tasks.yml
  when: ansible_distribution == "MacOSX"
