---
- hosts: all
  become: yes
  roles:
    - mounts
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      become: yes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      become: yes
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed on all servers
      become: yes
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      become: yes
      reboot:
      when: reboot_required_file.stat.exists

- hosts: control-k8s
  become: yes
  vars:
    k3s_become_for_all: true
    k3s_etcd_datastore: true
    k3s_use_experimental: true
  roles:
    - role: xanmanning.k3s

- hosts: dev-k8s
  become: yes
  vars:
    k3s_become_for_all: true
    k3s_etcd_datastore: true
    k3s_use_experimental: true
  roles:
    - role: xanmanning.k3s
  tasks:
    - name: Diable firewall
      become: true
      ufw:
        state: disabled

- hosts: prod-k8s
  become: yes
  vars:
    k3s_become_for_all: true
    k3s_etcd_datastore: true
    k3s_use_experimental: true
  roles:
    - role: xanmanning.k3s

- hosts: control-docker-hosts
  become: yes
  roles:
    - mounts
    - docker
    - sabnzbd
    - sonarr
    - radarr

- hosts: control-plex-1
  become: yes
  roles:
    - mounts
    - docker
    - plex
