---
- hosts: all
  become: yes
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      become: yes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      become: yes
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed on all servers
      become: yes
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      become: yes
      reboot:
      when: reboot_required_file.stat.exists

#- hosts: control-lb
#  become: yes
#  vars:
#    k3s_nodes: "{{ groups['control-k8s'] }}"
#  roles:
#    - { role: geerlingguy.nginx }
#  tasks:
#    - name: Template out config file
#      become: yes
#      template:
#        src: ./templates/nginx-loadbalancer-config.j2
#        dest: /etc/nginx/nginx.conf

- hosts: control-k8s
  become: yes
  vars:
    k3s_become_for_all: true
    k3s_etcd_datastore: true
    k3s_use_experimental: true
  roles:
    - role: xanmanning.k3s

#- hosts: dev-lb
#  become: yes
#  vars:
#    k3s_nodes: "{{ groups['control-k8s'] }}"
#  roles:
#    - { role: geerlingguy.nginx }
#  tasks:
#    - name: Template out config file
#      become: yes
#      template:
#        src: ./templates/nginx-loadbalancer-config.j2
#        dest: /etc/nginx/nginx.conf

- hosts: dev-k8s
  become: yes
  vars:
    k3s_become_for_all: true
    k3s_etcd_datastore: true
    k3s_use_experimental: true
  roles:
    - role: xanmanning.k3s
