# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/helper-plugin-utils-7.16.7" = {
      name = "_at_babel_slash_helper-plugin-utils";
      packageName = "@babel/helper-plugin-utils";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-plugin-utils/-/helper-plugin-utils-7.16.7.tgz";
        sha512 = "Qg3Nk7ZxpgMrsox6HreY1ZNKdBq7K72tDSliA6dCl5f007jR4ne8iD5UzuNnCJH2xBf2BEEVGr+/OL6Gdp7RxA==";
      };
    };
    "@babel/helper-validator-identifier-7.16.7" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.16.7.tgz";
        sha512 = "hsEnFemeiW4D08A5gUAZxLBTXpZ39P+a+DGDsHw1yxqyQ/jzFEnxf5uTEGp+3bzAbNOxU1paTgYS4ECU/IgfDw==";
      };
    };
    "@babel/plugin-syntax-jsx-7.14.5" = {
      name = "_at_babel_slash_plugin-syntax-jsx";
      packageName = "@babel/plugin-syntax-jsx";
      version = "7.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/plugin-syntax-jsx/-/plugin-syntax-jsx-7.14.5.tgz";
        sha512 = "ohuFIsOMXJnbOMRfX7/w7LocdR6R7whhuRD4ax8IipLcLPlZGJKkBxgHp++U4N/vKyU16/YDQr2f5seajD3jIw==";
      };
    };
    "@babel/types-7.15.0" = {
      name = "_at_babel_slash_types";
      packageName = "@babel/types";
      version = "7.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/types/-/types-7.15.0.tgz";
        sha512 = "OBvfqnllOIdX4ojTHpwZbpvz4j3EWyjkZEdmjH0/cgsd6QOdSgU8rLSk6ard/pcW7rlmjdVSX/AWOaORR1uNOQ==";
      };
    };
    "@next/env-12.0.8" = {
      name = "_at_next_slash_env";
      packageName = "@next/env";
      version = "12.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/env/-/env-12.0.8.tgz";
        sha512 = "Wa0gOeioB9PHap9wtZDZEhgOSE3/+qE/UALWjJHuNvH4J3oE+13EjVOiEsr1JcPCXUN8ESQE+phDKlo6qJ8P9g==";
      };
    };
    "@next/react-refresh-utils-12.0.8" = {
      name = "_at_next_slash_react-refresh-utils";
      packageName = "@next/react-refresh-utils";
      version = "12.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/react-refresh-utils/-/react-refresh-utils-12.0.8.tgz";
        sha512 = "Bq4T/aOOFQUkCF9b8k9x+HpjOevu65ZPxsYJOpgEtBuJyvb+sZREtDDLKb/RtjUeLMrWrsGD0aLteyFFtiS8Og==";
      };
    };
    "@next/swc-android-arm64-12.0.8" = {
      name = "_at_next_slash_swc-android-arm64";
      packageName = "@next/swc-android-arm64";
      version = "12.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-android-arm64/-/swc-android-arm64-12.0.8.tgz";
        sha512 = "BiXMcOZNnXSIXv+FQvbRgbMb+iYayLX/Sb2MwR0wja+eMs46BY1x/ssXDwUBADP1M8YtrGTlSPHZqUiCU94+Mg==";
      };
    };
    "@next/swc-darwin-arm64-12.0.8" = {
      name = "_at_next_slash_swc-darwin-arm64";
      packageName = "@next/swc-darwin-arm64";
      version = "12.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-darwin-arm64/-/swc-darwin-arm64-12.0.8.tgz";
        sha512 = "6EGMmvcIwPpwt0/iqLbXDGx6oKHAXzbowyyVXK8cqmIvhoghRFjqfiNGBs+ar6wEBGt68zhwn/77vE3iQWoFJw==";
      };
    };
    "@next/swc-darwin-x64-12.0.8" = {
      name = "_at_next_slash_swc-darwin-x64";
      packageName = "@next/swc-darwin-x64";
      version = "12.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-darwin-x64/-/swc-darwin-x64-12.0.8.tgz";
        sha512 = "todxgQOGP/ucz5UH2kKR3XGDdkWmWr0VZAAbzgTbiFm45Ol4ih602k2nNR3xSbza9IqNhxNuUVsMpBgeo19CFQ==";
      };
    };
    "@next/swc-linux-arm-gnueabihf-12.0.8" = {
      name = "_at_next_slash_swc-linux-arm-gnueabihf";
      packageName = "@next/swc-linux-arm-gnueabihf";
      version = "12.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-linux-arm-gnueabihf/-/swc-linux-arm-gnueabihf-12.0.8.tgz";
        sha512 = "KULmdrfI+DJxBuhEyV47MQllB/WpC3P2xbwhHezxL/LkC2nkz5SbV4k432qpx2ebjIRf9SjdQ5Oz1FjD8Urayw==";
      };
    };
    "@next/swc-linux-arm64-gnu-12.0.8" = {
      name = "_at_next_slash_swc-linux-arm64-gnu";
      packageName = "@next/swc-linux-arm64-gnu";
      version = "12.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-linux-arm64-gnu/-/swc-linux-arm64-gnu-12.0.8.tgz";
        sha512 = "1XO87wgIVPvt5fx5i8CqdhksRdcpqyzCOLW4KrE0f9pUCIT04EbsFiKdmsH9c73aqjNZMnCMXpbV+cn4hN8x1w==";
      };
    };
    "@next/swc-linux-arm64-musl-12.0.8" = {
      name = "_at_next_slash_swc-linux-arm64-musl";
      packageName = "@next/swc-linux-arm64-musl";
      version = "12.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-linux-arm64-musl/-/swc-linux-arm64-musl-12.0.8.tgz";
        sha512 = "NStRZEy/rkk2G18Yhc/Jzi1Q2Dv+zH176oO8479zlDQ5syRfc6AvRHVV4iNRc8Pai58If83r/nOJkwFgGwkKLw==";
      };
    };
    "@next/swc-linux-x64-gnu-12.0.8" = {
      name = "_at_next_slash_swc-linux-x64-gnu";
      packageName = "@next/swc-linux-x64-gnu";
      version = "12.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-linux-x64-gnu/-/swc-linux-x64-gnu-12.0.8.tgz";
        sha512 = "rHxTGtTEDFsdT9/VjewzxE19S7W1NE+aZpm4TwbT1pSNGK9KQxQGcXjqoHMeB+VZCFknzNEoIU/vydbjZMlAuw==";
      };
    };
    "@next/swc-linux-x64-musl-12.0.8" = {
      name = "_at_next_slash_swc-linux-x64-musl";
      packageName = "@next/swc-linux-x64-musl";
      version = "12.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-linux-x64-musl/-/swc-linux-x64-musl-12.0.8.tgz";
        sha512 = "1F4kuFRQE10GSx7LMSvRmjMXFGpxT30g8rZzq9r/p/WKdErA4WB4uxaKEX0P8AINfuN63i4luKdR+LoacgBhYw==";
      };
    };
    "@next/swc-win32-arm64-msvc-12.0.8" = {
      name = "_at_next_slash_swc-win32-arm64-msvc";
      packageName = "@next/swc-win32-arm64-msvc";
      version = "12.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-win32-arm64-msvc/-/swc-win32-arm64-msvc-12.0.8.tgz";
        sha512 = "QuRe49jqCV61TysGopC1P0HPqFAMZMWe1nbIQLyOkDLkULmZR8N2eYZq7fwqvZE5YwhMmJA/grwWFVBqSEh5Kg==";
      };
    };
    "@next/swc-win32-ia32-msvc-12.0.8" = {
      name = "_at_next_slash_swc-win32-ia32-msvc";
      packageName = "@next/swc-win32-ia32-msvc";
      version = "12.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-win32-ia32-msvc/-/swc-win32-ia32-msvc-12.0.8.tgz";
        sha512 = "0RV3/julybJr1IlPCowIWrJJZyAl+sOakJEM15y1NOOsbwTQ5eKZZXSi+7e23TN4wmy5HwNvn2dKzgOEVJ+jbA==";
      };
    };
    "@next/swc-win32-x64-msvc-12.0.8" = {
      name = "_at_next_slash_swc-win32-x64-msvc";
      packageName = "@next/swc-win32-x64-msvc";
      version = "12.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-win32-x64-msvc/-/swc-win32-x64-msvc-12.0.8.tgz";
        sha512 = "tTga6OFfO2JS+Yt5hdryng259c/tzNgSWkdiU2E+RBHiysAIOta57n4PJ8iPahOSqEqjaToPI76wM+o441GaNQ==";
      };
    };
    "@types/node-17.0.10" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "17.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-17.0.10.tgz";
        sha512 = "S/3xB4KzyFxYGCppyDt68yzBU9ysL88lSdIah4D6cptdcltc4NCPCAMc0+PCpg/lLIyC7IPvj2Z52OJWeIUkog==";
      };
    };
    "big.js-5.2.2" = {
      name = "big.js";
      packageName = "big.js";
      version = "5.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/big.js/-/big.js-5.2.2.tgz";
        sha512 = "vyL2OymJxmarO8gxMr0mhChsO9QGwhynfuu4+MHTAW6czfq9humCB7rKpUjDd9YUiDPU4mzpyupFSvOClAwbmQ==";
      };
    };
    "caniuse-lite-1.0.30001300" = {
      name = "caniuse-lite";
      packageName = "caniuse-lite";
      version = "1.0.30001300";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001300.tgz";
        sha512 = "cVjiJHWGcNlJi8TZVKNMnvMid3Z3TTdDHmLDzlOdIiZq138Exvo0G+G0wTdVYolxKb4AYwC+38pxodiInVtJSA==";
      };
    };
    "colorette-1.4.0" = {
      name = "colorette";
      packageName = "colorette";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/colorette/-/colorette-1.4.0.tgz";
        sha512 = "Y2oEozpomLn7Q3HFP7dpww7AtMJplbM9lGZP6RDfHqmbeRjiwRg4n6VM6j4KLmRke85uWEI7JqF17f3pqdRA0g==";
      };
    };
    "convert-source-map-1.7.0" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.7.0.tgz";
        sha512 = "4FJkXzKXEDB1snCFZlLP4gpC3JILicCpGbzG9f9G7tGqGCzETQ2hWPrcinA9oU4wtf2biUaEH5065UnMeR33oA==";
      };
    };
    "emojis-list-2.1.0" = {
      name = "emojis-list";
      packageName = "emojis-list";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emojis-list/-/emojis-list-2.1.0.tgz";
        sha1 = "4daa4d9db00f9819880c79fa457ae5b09a1fd389";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "jest-worker-27.0.0-next.5" = {
      name = "jest-worker";
      packageName = "jest-worker";
      version = "27.0.0-next.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/jest-worker/-/jest-worker-27.0.0-next.5.tgz";
        sha512 = "mk0umAQ5lT+CaOJ+Qp01N6kz48sJG2kr2n1rX0koqKf6FIygQV0qLOdN9SCYID4IVeSigDOcPeGLozdMLYfb5g==";
      };
    };
    "json5-1.0.1" = {
      name = "json5";
      packageName = "json5";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-1.0.1.tgz";
        sha512 = "aKS4WQjPenRxiQsC93MNfjx+nbF4PAdYzmd/1JIj8HYzqfbu86beTuNgXDzPknWk0n0uARlyewZo4s++ES36Ow==";
      };
    };
    "loader-utils-1.2.3" = {
      name = "loader-utils";
      packageName = "loader-utils";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/loader-utils/-/loader-utils-1.2.3.tgz";
        sha512 = "fkpz8ejdnEMG3s37wGL07iSBDg99O9D5yflE9RGNH3hRdx9SOwYfnGYdZOUIZitN8E+E2vkq3MUMYMvPYl5ZZA==";
      };
    };
    "merge-stream-2.0.0" = {
      name = "merge-stream";
      packageName = "merge-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-stream/-/merge-stream-2.0.0.tgz";
        sha512 = "abv/qOcuPfk3URPfDzmZU1LKmuw8kT+0nIHvKrKgFrwifol/doWcdA4ZqsWQ8ENrFKkd67Mfpo/LovbIUsbt3w==";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "nanoid-3.2.0" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.2.0.tgz";
        sha512 = "fmsZYa9lpn69Ad5eDn7FMcnnSR+8R34W9qJEijxYhTbfOWzr22n1QxCMzXLK+ODyW2973V3Fux959iQoUxzUIA==";
      };
    };
    "node-fetch-2.6.1" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.1.tgz";
        sha512 = "V4aYg89jEoVRxRb2fJdAg8FHvI7cEyYdVAh94HH0UIK8oJxUfkjlDQN9RbMx+bEjP7+ggMiFRprSti032Oipxw==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "postcss-8.2.15" = {
      name = "postcss";
      packageName = "postcss";
      version = "8.2.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-8.2.15.tgz";
        sha512 = "2zO3b26eJD/8rb106Qu2o7Qgg52ND5HPjcyQiK2B98O388h43A448LCslC0dI2P97wCAQRJsFvwTRcXxTKds+Q==";
      };
    };
    "react-is-17.0.2" = {
      name = "react-is";
      packageName = "react-is";
      version = "17.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-17.0.2.tgz";
        sha512 = "w2GsyukL62IJnlaff/nRegPQR94C/XXamvMWmSHRJ4y7Ts/4ocGRmTHvOs8PSE6pB3dWOrD/nueuU5sduBsQ4w==";
      };
    };
    "react-refresh-0.8.3" = {
      name = "react-refresh";
      packageName = "react-refresh";
      version = "0.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-refresh/-/react-refresh-0.8.3.tgz";
        sha512 = "X8jZHc7nCMjaCqoU+V2I0cOhNW+QMBwSUkeXnTi8IPe6zaRWfn60ZzvFDZqWPfmSJfjub7dDW1SP0jaHWLu/hg==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-0.7.3" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.7.3.tgz";
        sha512 = "CkCj6giN3S+n9qrYiBTX5gystlENnRW5jZeNLHpe6aue+SrHcG5VYwujhW9s4dY31mEGsxBDrHR6oI69fTXsaQ==";
      };
    };
    "stream-browserify-3.0.0" = {
      name = "stream-browserify";
      packageName = "stream-browserify";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-browserify/-/stream-browserify-3.0.0.tgz";
        sha512 = "H73RAHsVBapbim0tU2JwwOiXUj+fikfiaoYAKHF3VJfA0pe2BCzkhAHBlLG6REzE+2WNZcxOXjK7lkso+9euLA==";
      };
    };
    "string-hash-1.1.3" = {
      name = "string-hash";
      packageName = "string-hash";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-hash/-/string-hash-1.1.3.tgz";
        sha1 = "e8aafc0ac1855b4666929ed7dd1275df5d6c811b";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "styled-jsx-5.0.0-beta.6" = {
      name = "styled-jsx";
      packageName = "styled-jsx";
      version = "5.0.0-beta.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/styled-jsx/-/styled-jsx-5.0.0-beta.6.tgz";
        sha512 = "b1cM7Xyp2r1lsNpvoZ6wmTI8qxD0557vH2feHakNU8LMkzfJDgTQMul6O7sSYY0GxQ73pKEN69hCDp71w6Q0nA==";
      };
    };
    "stylis-3.5.4" = {
      name = "stylis";
      packageName = "stylis";
      version = "3.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylis/-/stylis-3.5.4.tgz";
        sha512 = "8/3pSmthWM7lsPBKv7NXkzn2Uc9W7NotcwGNpJaa3k7WMM1XDCA4MgT5k/8BIexd5ydZdboXtU90XH9Ec4Bv/Q==";
      };
    };
    "stylis-rule-sheet-0.0.10" = {
      name = "stylis-rule-sheet";
      packageName = "stylis-rule-sheet";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylis-rule-sheet/-/stylis-rule-sheet-0.0.10.tgz";
        sha512 = "nTbZoaqoBnmK+ptANthb10ZRZOGC+EmTLLUxeYIuHNkEKcmKgXX1XWKkUBT2Ac4es3NybooPe0SmvKdhKJZAuw==";
      };
    };
    "supports-color-8.1.1" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "8.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-8.1.1.tgz";
        sha512 = "MpUEN2OodtUzxvKQl72cUF7RQ5EiHsGvSsVG0ia9c5RbWGL2CI4C7EpPS8UTBIplnlzZiNuV56w+FuNxy3ty2Q==";
      };
    };
    "to-fast-properties-2.0.0" = {
      name = "to-fast-properties";
      packageName = "to-fast-properties";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-fast-properties/-/to-fast-properties-2.0.0.tgz";
        sha1 = "dc5e698cbd079265bc73e0377681a4e4e83f616e";
      };
    };
    "use-subscription-1.5.1" = {
      name = "use-subscription";
      packageName = "use-subscription";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/use-subscription/-/use-subscription-1.5.1.tgz";
        sha512 = "Xv2a1P/yReAjAbhylMfFplFKj9GssgTwN7RlcTxBujFQcloStWNDQdc4g4NRWH9xS4i/FDk04vQBptAXoF3VcA==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
  };
in
{
  next = nodeEnv.buildNodePackage {
    name = "next";
    packageName = "next";
    version = "12.0.8";
    src = fetchurl {
      url = "https://registry.npmjs.org/next/-/next-12.0.8.tgz";
      sha512 = "g5c1Kuh1F8tSXJn2rVvzYBzqe9EXaR6+rY3/KrQ7y0D9FueRLfHI35wM0DRadDcPSc3+vncspfhYH3jnYE/KjA==";
    };
    dependencies = [
      sources."@babel/helper-plugin-utils-7.16.7"
      sources."@babel/helper-validator-identifier-7.16.7"
      sources."@babel/plugin-syntax-jsx-7.14.5"
      sources."@babel/types-7.15.0"
      sources."@next/env-12.0.8"
      sources."@next/react-refresh-utils-12.0.8"
      sources."@next/swc-android-arm64-12.0.8"
      sources."@next/swc-darwin-arm64-12.0.8"
      sources."@next/swc-darwin-x64-12.0.8"
      sources."@next/swc-linux-arm-gnueabihf-12.0.8"
      sources."@next/swc-linux-arm64-gnu-12.0.8"
      sources."@next/swc-linux-arm64-musl-12.0.8"
      sources."@next/swc-linux-x64-gnu-12.0.8"
      sources."@next/swc-linux-x64-musl-12.0.8"
      sources."@next/swc-win32-arm64-msvc-12.0.8"
      sources."@next/swc-win32-ia32-msvc-12.0.8"
      sources."@next/swc-win32-x64-msvc-12.0.8"
      sources."@types/node-17.0.10"
      sources."big.js-5.2.2"
      sources."caniuse-lite-1.0.30001300"
      sources."colorette-1.4.0"
      (sources."convert-source-map-1.7.0" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      sources."emojis-list-2.1.0"
      sources."has-flag-4.0.0"
      sources."inherits-2.0.4"
      sources."jest-worker-27.0.0-next.5"
      sources."json5-1.0.1"
      sources."loader-utils-1.2.3"
      sources."merge-stream-2.0.0"
      sources."minimist-1.2.5"
      sources."nanoid-3.2.0"
      sources."node-fetch-2.6.1"
      sources."object-assign-4.1.1"
      sources."postcss-8.2.15"
      sources."react-is-17.0.2"
      sources."react-refresh-0.8.3"
      sources."readable-stream-3.6.0"
      sources."safe-buffer-5.2.1"
      sources."source-map-0.6.1"
      sources."stream-browserify-3.0.0"
      sources."string-hash-1.1.3"
      sources."string_decoder-1.3.0"
      (sources."styled-jsx-5.0.0-beta.6" // {
        dependencies = [
          sources."source-map-0.7.3"
        ];
      })
      sources."stylis-3.5.4"
      sources."stylis-rule-sheet-0.0.10"
      sources."supports-color-8.1.1"
      sources."to-fast-properties-2.0.0"
      sources."use-subscription-1.5.1"
      sources."util-deprecate-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The React Framework";
      homepage = "https://nextjs.org";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
