---
- name: Add a MX record for pointing email to fastmail
  community.aws.route53:
    aws_access_key: "{{ keys.ben_harvy_ninja.admin.key }}"
    aws_secret_key: "{{ keys.ben_harvy_ninja.admin.secret }}"
    zone: "{{ harvey_onl_zone }}"
    state: present
    record: harvey.onl
    type: MX
    value:
      - 10 in1-smtp.messagingengine.com
      - 20 in2-smtp.messagingengine.com

- name: Add a CNAME record for pointing email to fastmail - fml1
  community.aws.route53:
    aws_access_key: "{{ keys.ben_harvy_ninja.admin.key }}"
    aws_secret_key: "{{ keys.ben_harvy_ninja.admin.secret }}"
    state: present
    zone: "{{ harvey_onl_zone }}"
    record: fm1._domainkey.harvey.onl
    type: CNAME
    ttl: 30
    value: fm1.harvey.onl.dkim.fmhosted.com

- name: Add a CNAME record for pointing email to fastmail - fml2
  community.aws.route53:
    aws_access_key: "{{ keys.ben_harvy_ninja.admin.key }}"
    aws_secret_key: "{{ keys.ben_harvy_ninja.admin.secret }}"
    state: present
    zone: "{{ harvey_onl_zone }}"
    record: fm2._domainkey.harvey.onl
    type: CNAME
    ttl: 30
    value: fm2.harvey.onl.dkim.fmhosted.com

- name: Add a CNAME record for pointing email to fastmail - fml3
  community.aws.route53:
    aws_access_key: "{{ keys.ben_harvy_ninja.admin.key }}"
    aws_secret_key: "{{ keys.ben_harvy_ninja.admin.secret }}"
    state: present
    zone: "{{ harvey_onl_zone }}"
    record: fm3._domainkey.harvey.onl
    type: CNAME
    ttl: 30
    value: fm3.harvey.onl.dkim.fmhosted.com

- name: Add txt record to configure email spf record
  community.aws.route53:
    aws_access_key: "{{ keys.ben_harvy_ninja.admin.key }}"
    aws_secret_key: "{{ keys.ben_harvy_ninja.admin.secret }}"
    zone: "{{ harvey_onl_zone }}"
    state: present
    record: harvey.onl
    type: TXT
    ttl: 30
    value: '"v=spf1 include:spf.messagingengine.com ?all"'
