---
- name: Install terraform gpg key
  become: yes
  shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
  register: shell_result

- debug:
    var: shell_result.stdout_lines

- name: Install terraform apt repository
  become: yes
  shell: apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
  register: shell_result

- debug:
    var: shell_result.stdout_lines

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install common packages
  become: true
  package:
    name: "{{ apt_packages }}"
    state: present

- name: Install base snap package
  become: true
  package:
    name: snapd
    state: present

- name: Install snap packages
  become: yes
  community.general.snap:
    name: "{{ snap_packages }}"

- name: Install snap packages with --classic flag
  become: yes
  community.general.snap:
    name: "{{ snap_packages_classic }}"
    classic: yes
