---
- name: Ensure nfs client packages are available
  become: true
  package:
    name: nfs-common
    state: present

- name: Mount an NFS volume
  become: yes
  ansible.posix.mount:
    src: truenas:/mnt/storage-01/ds-01
    path: /mnt/storage-01
    opts: rw,sync,hard,intr
    state: mounted
    fstype: nfs
    backup: yes
